Fix build and typescript errors
The following errors were found and fixed:
- src/components/auth/LoginModal.tsx(77,21): error TS2345: Argument of type 'Error' is not assignable to parameter of type 'SetStateAction<string>'.
- src/components/auth/LoginModal.tsx(148,9): error TS2322: Type '{ onBack: () => void; onSuccess: () => void; }' is not assignable to type 'IntrinsicAttributes & ForgotPasswordFormProps'. Property 'onBack' does not exist on type 'IntrinsicAttributes & ForgotPasswordFormProps'.
- src/components/auth/LoginModal.tsx(211,11): error TS2322: Type '() => Promise<void>' is not assignable to type '(email: string) => Promise<{ error: Error; }>'. Type 'Promise<void>' is not assignable to type 'Promise<{ error: Error; }>'. Type 'void' is not assignable to type '{ error: Error; }'.
- src/components/auth/SignupModal.tsx(51,21): error TS2345: Argument of type 'Error' is not assignable to parameter of type 'SetStateAction<ReactNode>'.
- src/components/auth/SignupModal.tsx(52,25): error TS2339: Property 'requiresVerification' does not exist on type '{ error: Error; user?: User; }'.
- src/components/auth/SignupModal.tsx(97,18): error TS2339: Property 'requiresVerification' does not exist on type '{ error: Error; user?: User; }'.
- src/components/chat/AstroDataForm.tsx(109,11): error TS2353: Object literal may only specify known properties, and 'chat_id' does not exist in type 'ReportFormData'.